name: Lambda Function Continuous Deployment

env:
  AWS_REGION: us-west-2
  AWS_LAMBDA_FUNCTION_NAME: csye6225-Lambda-function

on:
  push:
    branches: [main, Assignment-09]
jobs:  
  lambda_deploy:
    runs-on: ubuntu-latest
    name: Deploy Lambda Function
    steps:
      - name: Step 1 - Checkout code from branch
        uses: actions/checkout@v2
      
      - name: Step 2 - Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_DEMO_USER_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_DEMO_USER_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Step 3 - Zip the serverless code
        run: |
          ls -al
          zip function.zip index.js
          ls -al

      - name: Step 4 - Deploy the Lambda function
        run: |
          aws lambda update-function-code --function-name=${{ env.AWS_LAMBDA_FUNCTION_NAME }} --zip-file=fileb://function.zip 

      - name: Step 5 - Cleanup
        run: |
          rm function.zip
          ls -al  